repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: mixed-line-ending
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    exclude: "src/postcodes_nov_2022.py"
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      args:
      - -s
      - B101
